name          'puppet-influxdb'
version       '0.1.1'
source        'http://github.com/cotocisternas/puppet-influxdb'
author        'cotocisternas'
license       'Apache 2.0'
summary       'influxdb module'
description   'influxdb module'
project_page  'https://github.com/cotocisternas/puppet-influxdb'

dependency 'puppetlabs/stdlib'
